---

- name: firewalld
  package:
    name: firewalld

- name: service
  service:
    name: firewalld
    state: started

- name: zone
  firewalld:
    permanent: true
    interface: eth0
    zone: public
    state: enabled

- name: ssh
  firewalld:
    permanent: true
    immediate: true
    service: ssh
    state: enabled
  notify: firewalld.restart

- name: http
  firewalld:
    permanent: true
    immediate: true
    service: http
    state: enabled
  notify: firewalld.restart

- name: https
  firewalld:
    permanent: true
    immediate: true
    service: https
    state: enabled
  notify: firewalld.restart

- name: service
  service:
    name: firewalld
    enabled: true
    state: started
  notify: firewalld.restart
