---

- name: firewalld
  package:
    name: firewalld

- name: service
  service:
    name: firewalld
    state: started

- name: zone
  firewalld:
    permanent: true
    interface: eth0
    zone: public
    state: enabled

- name: ssh
  firewalld:
    permanent: true
    immediate: true
    service: ssh
    state: enabled
  when: not _firewall_skip_ssh
  notify:
    - firewalld.restart
    - firewalld.restart.skipped

- name: http
  firewalld:
    permanent: true
    immediate: true
    service: http
    state: enabled
  when: not _firewall_skip_http
  notify:
    - firewalld.restart
    - firewalld.restart.skipped

- name: https
  firewalld:
    permanent: true
    immediate: true
    service: https
    state: enabled
  when: not _firewall_skip_https
  notify:
    - firewalld.restart
    - firewalld.restart.skipped

- name: other services
  firewalld:
    permanent: true
    immediate: true
    service: "{{ item.service if item.service | default('') else omit }}"
    port: "{{ item.port if item.port | default('') else omit }}"
    state: "{{ item.state if item.state | default('') else omit }}"
    zone: "{{ item.zone if item.zone | default('') else omit }}"
  notify:
    - firewalld.restart
    - firewalld.restart.skipped
  loop: "{{ _firewall_services }}"

- name: service
  service:
    name: firewalld
    enabled: true
    state: started
  notify:
    - firewalld.restart
    - firewalld.restart.skipped
