---
- name: "postgresql_cluster · user {{ _user.username }}"
  postgresql_user:
    name: "{{ _user.username }}"
    port: "{{ _cluster_port }}"
    role_attr_flags: "{{ _user.roles | default(postgresql_cluster_default_user_roles) }}"
    password: "{{ _user.password }}"
  become: true
  become_user: root
  vars:
    _cluster: "{{ cluster_user_item.cluster }}"
    _user: "{{ cluster_user_item.user }}"
    _cluster_port: "{{ _cluster.port | default(postgresql_cluster_default_port) }}"
