- name: httpd · install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ _httpd_packages | distro(vars) }}"
  become: yes
  become_user: root
  when: httpd_step_install

- name: enable modules
  file:
    path: "/etc/apache2/mods-enabled/{{ item | basename }}"
    state: link
    src: "{{ item }}"
  with_items:
    - /etc/apache2/mods-available/rewrite.load
    - /etc/apache2/mods-available/proxy.conf
    - /etc/apache2/mods-available/proxy.load
    - /etc/apache2/mods-available/proxy_ajp.load
    # needed by ssl
    - /etc/apache2/mods-available/socache_shmcb.load
    - /etc/apache2/mods-available/ssl.conf
    - /etc/apache2/mods-available/ssl.load
  when: ansible_os_family == 'Debian'

- block:
  - name: httpd · selinux ports
    seport:
      ports: "{{ _port }}"
      proto: tcp
      setype: http_port_t
      state: present
    with_items:
      - "{{ _httpd_ajp_port }}"
    loop_control:
      loop_var: _port
    when: x_selinux_handle

  - name: httpd · configuration
    template:
      src: application.conf.j2
      dest: "{{ _httpd_configuration_folder }}/50-{{ _httpd_application_name }}.conf"
      owner: root
      group: root
      mode: u=rw,g=r,o=r
    vars:
      _server_name: "{{ httpd_server_name }}"
      _server_aliases: "{{ httpd_server_aliases }}"
      _server_https_domain_redirect: "{{ httpd_https_domain_redirect }}"
      _ssl_certificate: "{{ _httpd_ssl_certificate }}"
      _ssl_key: "{{ _httpd_ssl_key }}"
      _ssl_cacertificate: "{{ _httpd_ssl_cacertificate }}"
    notify: httpd
    become: yes
    become_user: root

  - name: httpd · status page
    template:
      src: server-status.conf.j2
      dest: "{{ _httpd_configuration_folder }}/25-server-status.conf"
      owner: root
      group: root
      mode: u=rw,g=r,o=r
    notify: httpd
    become: yes
    become_user: root

  - name: httpd · remove default conf
    file:
      path: "{{ _httpd_configuration_folder }}/{{ item }}"
      state: absent
    with_items:
      - autoindex.conf
      - README
      - userdir.conf
      - welcome.conf
      - 000-default.conf
    become: yes
    become_user: root

  - name: httpd · service
    service:
      name: "{{ _httpd_service }}"
      enabled: yes
      state: started
    become: yes
    become_user: root

  when: httpd_step_configuration
