---

- name: httpd · general configuration
  template:
    src: "{{ _httpd_common_template }}"
    dest: "{{ _httpd_configuration_folder }}/00-common.conf"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - httpd.restart
    - httpd.restart.skipped
  become: true
  become_user: root

- name: httpd · configuration
  template:
    src: application.conf.j2
    dest: "{{ _httpd_configuration_folder }}/50-{{ _httpd_application_name }}.conf"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  vars:
    _server_name: "{{ httpd_server_name }}"
    _server_aliases: "{{ httpd_server_aliases }}"
    _server_https_domain_redirect: "{{ httpd_https_domain_redirect }}"
    _ssl_certificate: "{{ _httpd_ssl_certificate }}"
    _ssl_key: "{{ _httpd_ssl_key }}"
    _ssl_chain: "{{ _httpd_ssl_chain }}"
    _ssl_cacertificate: "{{ _httpd_ssl_cacertificate }}"
    _ssl_protocol: "{{ _httpd_ssl_protocol }}"
    _ssl_ciphersuite: "{{ _httpd_ssl_ciphersuite }}"
  notify:
    - httpd.restart
    - httpd.restart.skipped
  become: yes
  become_user: root
  when: httpd_manage_vhost_configuration | default(true)

- name: httpd · configuration robots.txt
  copy:
    content: "{{ _httpd_conf_robots_txt }}"
    dest: "{{ _httpd_documentroot }}/robots.txt"
    owner: "{{ _httpd_user }}"
    group: "{{ _httpd_user }}"
    mode: u=rw,g=r,o=r
  become: yes
  become_user: root
  when: _httpd_conf_robots_txt | default('') != ''

- name: httpd · configuration {{ vhost_item.filename }}
  template:
    src: "{{ vhost_item.template | default('custom.conf.j2') }}"
    dest: "{{ _httpd_configuration_folder }}/{{ vhost_item.filename }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - httpd.restart
    - httpd.restart.skipped
  become: yes
  become_user: root
  with_items: "{{ _httpd_custom_vhosts }}"
  loop_control:
    loop_var: vhost_item
    label: "{{ vhost_item.filename }}"

- name: httpd · configuration {{ vhost_item.filename }} robots.txt
  copy:
    content: "{{ vhost_item.robots_txt }}"
    dest: "{{ vhost_item.documentRoot }}/robots.txt"
    owner: "{{ _httpd_user }}"
    group: "{{ _httpd_user }}"
    mode: u=rw,g=r,o=r
  become: yes
  become_user: root
  with_items: "{{ _httpd_custom_vhosts }}"
  when: vhost_item['robots_txt'] | default('') != ''
  loop_control:
    loop_var: vhost_item
    label: "{{ vhost_item.filename }} robots.txt"
