---

- name: glowroot agent · log dir
  file:
    path: "{{ _glowroot_config_log_dir }}"
    owner: "{{ _glowroot_agent_user }}"
    group: "{{ _glowroot_agent_group }}"
    mode: u=rwx,g=rx,o=rx
    state: directory
  become: true
  become_user: root

- name: glowroot agent · tmp dir
  file:
    path: "{{ _glowroot_config_tmp_dir }}"
    owner: "{{ _glowroot_agent_user }}"
    group: "{{ _glowroot_agent_group }}"
    mode: u=rwx,g=rx,o=rx
    state: directory
  become: true
  become_user: root

- name: glowroot agent · conf dir
  file:
    path: "{{ _glowroot_config_conf_dir }}"
    owner: "{{ _glowroot_agent_user }}"
    group: "{{ _glowroot_agent_group }}"
    mode: u=rwx,g=rx,o=rx
    state: directory
  become: true
  become_user: root
