---
- name: firewalld.restart
  service:
    name: firewalld
    state: restarted
  become: true
  become_user: root
  when: not _firewall_handlers_inhibited

- name: firewalld.restart.skipped
  debug:
    msg: Restart inhibited by configuration; you must restart manually firewalld
  changed_when: true
  when: _firewall_handlers_inhibited

- name: firewalld.start
  service:
    name: firewalld
    state: started
  become: true
  become_user: root
  when: not _firewall_handlers_inhibited

- name: firewalld.start.skipped
  debug:
    msg: Start inhibited by configuration; you must start manually firewalld
  changed_when: true
  when: _firewall_handlers_inhibited

- name: firewalld.stop
  service:
    name: firewalld
    state: stopped
  become: true
  become_user: root
  when: not _firewall_handlers_inhibited

- name: firewalld.stop.skipped
  debug:
    msg: Stop inhibited by configuration; you must stop manually firewalld
  changed_when: true
  when: _firewall_handlers_inhibited
