---
- name: copy package
  copy:
    src: "{{ item }}"
    dest: /data/opt/packages/
  # Initial delivery: user is unprivileged, but he can sudo, ansible_user not set
  # Continuous delivery: use has write permission on folder and can't sudo
  become: "{{ ansible_user | default('') != playbook_remote_user }}"


- name: install package
  shell:
    sudo apt-get install -y --allow-downgrades /data/opt/packages/{{ item | basename }}
  # sudo setup is highly restrictive on filename and location
  when: item | basename == playbook_application_name + '-static.deb'
  register: apt_install
