---
## systemd
- name: reload tomcat instances
  become: yes
  become_user: root
  systemd:
    name: tomcat@{{ item.name }}
    state: reloaded
  with_items: "{{ tomcat_catalina_bases }}"
  when: "{{ _tomcat_systemd }}"

- name: restart tomcat instances
  become: yes
  become_user: root
  systemd:
    name: tomcat@{{ item.name }}
    state: restarted
  with_items: "{{ tomcat_catalina_bases }}"
  when: "{{ _tomcat_systemd }}"

- name: start tomcat instances
  become: yes
  become_user: root
  systemd:
    name: tomcat@{{ item.name }}
    state: started
  with_items: "{{ tomcat_catalina_bases }}"
  when: "{{ _tomcat_systemd }}"

- name: stop tomcat instances
  become: yes
  become_user: root
  systemd:
    name: tomcat@{{ item.name }}
    state: stopped
  with_items: "{{ tomcat_catalina_bases }}"
  when: "{{ _tomcat_systemd }}"

## initd
- name: reload tomcat instances
  become: yes
  become_user: root
  service:
    name: "{{ item.name }}"
    state: reloaded
  with_items: "{{ tomcat_catalina_bases }}"
  when: "{{ _tomcat_initd }}"

- name: restart tomcat instances
  become: yes
  become_user: root
  service:
    name: "{{ item.name }}"
    state: restarted
  with_items: "{{ tomcat_catalina_bases }}"
  when: "{{ _tomcat_initd }}"

- name: start tomcat instances
  become: yes
  become_user: root
  service:
    name: "{{ item.name }}"
    state: started
  with_items: "{{ tomcat_catalina_bases }}"
  when: "{{ _tomcat_initd }}"

- name: stop tomcat instances
  become: yes
  become_user: root
  service:
    name: "{{ item.name }}"
    state: stopped
  with_items: "{{ tomcat_catalina_bases }}"
  when: "{{ _tomcat_initd }}"
