---

##
## bug fixed: https://github.com/ansible/ansible/issues/16612
## We now use an inventory definition for x_selinux_handle, set from
## ansible_selinux definition.
##

- name: check x_selinux_handle
  fail:
    msg: "Use this role with an updated igloo-ansible-playbooks that defines x_selinux_handle!"
  when: x_selinux_handle is not defined
