- block:
  - name: tomcat · catalina_base · directory "{{ _catalina_base_path }}"
    file:
      path: "{{ item }}"
      owner: "{{ _catalina_base_user }}"
      group: "{{ _catalina_base_group }}"
      mode: u=rwx,g=rwx,o=rx
      state: directory
    with_items:
      - "{{ _catalina_base_path }}"
    become: yes
    become_user: root

  - name: tomcat · catalina_base · subdirectories "{{ _catalina_base_path }}"
    file:
      path: "{{ item }}"
      owner: "{{ _catalina_base_user }}"
      group: "{{ _catalina_base_group }}"
      mode: u=rwx,g=rwx,o=rx
      state: directory
    with_items:
      - "{{ _catalina_base_path }}/bin"
      - "{{ _catalina_base_path }}/conf"
      - "{{ _catalina_base_path }}/lib"
      - "{{ _catalina_base_path }}/logs"
      - "{{ _catalina_base_path }}/webapps"
      - "{{ _catalina_base_path }}/work"
      - "{{ _catalina_base_path }}/temp"
      - "{{ _catalina_base_path }}/pid"
    become: yes
    become_user: "{{ _catalina_base_user }}"

  - name: configuration tomcat (server.xml updated)
    template:
      src: "{{ _catalina_base_server_xml }}"
      dest: "{{ _catalina_base_path }}/conf/server.xml"
      owner: "{{ _catalina_base_user }}"
      group: "{{ _catalina_base_user }}"
      mode: u=rw,g=rw,o=r
    when: _catalina_base_server_xml != False
    become: yes
    become_user: "{{ _catalina_base_user }}"

  # conf/ file inventory
  - name: tomcat · catalina_base · {{ tomcat_dest }}/conf/ inventory"
    find:
      recurse: no
      paths:
        - "{{ tomcat_dest }}/conf"
      file_type: file
    register: catalina_home_files
    become: yes
    become_user: "{{ _catalina_base_user }}"

  # current {catalina_base}/conf/ status
  - name: "tomcat · catalina_base · files {{ _catalina_base_path }}"
    stat:
      path: "{{ _catalina_base_path }}/{{ item.path | relpath(tomcat_dest) }}"
    with_items: "{{ catalina_home_files.files }}"
    loop_control:
      label: "{{ item.path | relpath(tomcat_dest) }}"
    register: catalina_base_files
    become: yes
    become_user: "{{ _catalina_base_user }}"

  # copy missing conf/ files by using catalina_home as source
  - name: "tomcat · catalina_base · init file {{ _catalina_base_path }}"
    copy:
      dest: "{{ _catalina_base_path }}/{{ item.item.path | relpath(tomcat_dest) }}"
      src: "{{ tomcat_dest }}/{{ item.item.path | relpath(tomcat_dest) }}"
      remote_src: yes
      owner: "{{ _catalina_base_user }}"
      group: "{{ _catalina_base_group }}"
      mode: u=rw,g=rw,o=r
    with_items: "{{ catalina_base_files.results }}"
    loop_control:
      label: "{{ item.item.path | relpath(tomcat_dest) }}"
    when: not item.stat.exists and not item.invocation.module_args.path | basename == 'logging.properties'
    become: yes
    become_user: "{{ _catalina_base_user }}"

  # tomcat needs at least the global web.xml
  - name: tomcat · catalina_base · copy web.xml
    copy:
      src: "{{ tomcat_dest }}/conf/web.xml"
      dest: "{{ _catalina_base_path }}/conf/web.xml"
      owner: "{{ _catalina_base_user }}"
      group: "{{ _catalina_base_group }}"
      remote_src: yes
      force: no
    become: yes
    become_user: root

  - name: tomcat · catalina_base · service configuration file
    template:
      src: setenv.sh.j2
      dest: "{{ _catalina_base_path }}/bin/setenv.sh"
      owner: "{{ _catalina_base_user }}"
      group: "{{ _catalina_base_group }}"
      mode: u=rw,g=rw,o=r
    become: yes
    become_user: "{{ _catalina_base_user }}"
    vars:
      _java_home: "{{ _catalina_base_java_home }}"

  - block:

    - name: tomcat · catalina_base · service configuration directory
      file:
        path: /etc/systemd/system/tomcat@{{ catalina_base.name }}.service.d
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
      become: yes
      become_user: root

    - name: tomcat · catalina_base · service configuration file
      copy:
        dest: /etc/systemd/system/tomcat@{{ catalina_base.name }}.service.d/10-default.conf
        owner: root
        group: root
        mode: u=rw,g=rw,o=r
        content: "{{ _tomcat_systemd_env }}"
      vars:
        _catalina_home: "{{ tomcat_dest }}"
        _catalina_base: "{{ _catalina_base_path }}"
        _java_home: "{{ _catalina_base_java_home }}"
      become: yes
      become_user: root

    - name: tomcat · systemd configuration
      systemd:
        name: tomcat@{{ catalina_base.name }}
        daemon_reload: "{{ service_file.changed }}"
        enabled: true
        # state: "{{ 'restarted' if service_file.changed else 'started' }}"
      become: yes
      become_user: root

    - name: tomcat · sudoers
      lineinfile:
        dest: /etc/sudoers
        line: "{{ item.line }}"
        regexp: "^{{ item.line }}"
        insertafter: EOF
        state: present
      with_items:
        - { line: '# {{ playbook_remote_user }} user' }
        - { line: '{{ playbook_remote_user }} ALL=NOPASSWD: /usr/bin/systemctl restart tomcat@{{playbook_application_name}}' }
        - { line: '{{ playbook_remote_user }} ALL=NOPASSWD: /usr/bin/systemctl start tomcat@{{playbook_application_name}}' }
        - { line: '{{ playbook_remote_user }} ALL=NOPASSWD: /usr/bin/systemctl stop tomcat@{{playbook_application_name}}' }
        - { line: '{{ playbook_remote_user }} ALL=NOPASSWD: /usr/bin/systemctl status tomcat@{{playbook_application_name}}' }

    when: _tomcat_systemd

  - block:

    - name: tomcat · catalina_base · service configuration folder
      file:
        path: /etc/tomcat
        state: directory
        owner: root
        group: root
        mode: u=rwX,g=rwX,o=r
      become: yes
      become_user: root

    - name: tomcat · catalina_base · service configuration file
      copy:
        dest: /etc/tomcat/{{ catalina_base.name }}.conf
        owner: root
        group: root
        mode: u=rw,g=rw,o=r
        content: "{{ _tomcat_initd_env }}"
      vars:
        _catalina_home: "{{ tomcat_dest }}"
        _catalina_base: "{{ _catalina_base_path }}"
        _java_home: "{{ _catalina_base_java_home }}"
      become: yes
      become_user: root

    - name: tomcat · catalina_base · initd file
      file:
        state: link
        src: "{{ _tomcat_initscript }}"
        dest: /etc/init.d/{{ catalina_base.name }}
      become: yes
      become_user: root

    when: _tomcat_initd

  vars:
    _catalina_base_path: "{{ catalina_base.path | default((tomcat_catalina_base_root, catalina_base.name) | join('/')) }}"
    _catalina_base_user: "{{ catalina_base.user | default(tomcat_default_user) }}"
    _catalina_base_group: "{{ catalina_base.group | default(tomcat_default_group) }}"
    _catalina_base_java_home: "{{ catalina_base.java_home | default(tomcat_default_java_home) }}"
