- name: tomcat · download binary
  get_url:
    url: "{{ _tomcat7_download_url }}"
    dest: "{{ _tomcat7_download_target }}"
    checksum: "{{ tomcat7_checksum }}"
    owner: root
    group: root
    mode: u=rx,g=r,o=r
  become: yes
  become_user: root

- block:
  - name: tomcat · create directory
    file:
      dest: "{{ tomcat7_dest }}"
      state: directory
      owner: root
      group: root
      mode: u+rwx,g+rx,o+rx

  - name: tomcat · install binary
    unarchive:
      remote_src: true
      src: "{{ _tomcat7_download_target }}"
      dest: "{{ tomcat7_dest }}"
      # conf files are not world-readable by default
      mode: o+r
      extra_opts:
        - --strip-components=1

  when: ansible_distribution_major_version != "5"
  become: yes
  become_user: root

# strip-components is not available in CentOS 5, we need a workaround
# untar in alternate folder
# find parent of bin folder
# symlink tomcat7_dest to found folder
- block:
  - name: tomcat · prepare {{ tomcat7_wa_dest }} folder
    file:
      path: "{{ tomcat7_wa_dest }}"
      state: directory
      mode: u=rwx,g=rwx,o=rx
      owner: root
      group: root

  - name: tomcat · install in {{ tomcat7_wa_dest }}
    unarchive:
      remote_src: true
      dest: "{{ tomcat7_wa_dest }}"
      src: "{{ _tomcat7_download_target }}"

  - name: tomcat · find target for {{ tomcat7_dest }}
    command: "find {{ tomcat7_wa_dest }} -maxdepth 2 -name bin -type d -exec dirname {} \\;"
    register: find_result
    changed_when: no
    check_mode: no

  - name: tomcat · check {{ find_result.stdout_lines[0] }}
    file:
      state: directory
      path: "{{ find_result.stdout_lines[0] }}"

  - name: tomcat · symlink {{ tomcat7_dest }}
    file:
      state: link
      path: "{{ tomcat7_dest }}"
      src: "{{ find_result.stdout_lines[0] }}"

  vars:
    tomcat7_wa_dest: "{{ tomcat7_dest.rstrip('/') | dirname }}/wa-{{ tomcat7_dest.rstrip('/') | basename }}"

  when: ansible_distribution_major_version == "5"
  become: yes
  become_user: root

- name: tomcat7 · install tomcat7@.service
  template:
    src: tomcat7@.service
    dest: /etc/systemd/system/tomcat7@.service
    owner: root
    group: root
    mode: u=rw,g=rw,o=r
  vars:
    _user: "{{ tomcat7_default_user }}"
  register: service_file
  become: yes
  become_user: root
  when: _tomcat7_systemd

- name: tomcat7 · catalina_base · initd file
  template:
    dest: "{{ _tomcat7_initscript }}"
    owner: root
    group: root
    mode: u=rwx,g=rwx,o=r
    src: tomcat7.j2
  become: yes
  become_user: root
  when: _tomcat7_initd

- name: tomcat7 · prepare instances
  include: catalina_base_item.yml
  with_items: "{{ tomcat7_catalina_bases }}"
  loop_control:
    loop_var: catalina_base
