---
- name: logrotate.d config
  become_user: root
  copy:
    dest: /etc/logrotate.d/{{ _logrotate_item.filename }}
    content: |
      {{ _logrotate_item.pattern }} {{ _logrotate_item.config }}
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  vars:
    template_vars: "{{ _logrotate_item.template_vars }}"
