---
- name: install
  become_user: root
  package:
    name: logrotate

- name: configurations
  include_tasks: logrotate_item.yml
  with_items: "{{ _logrotate_items }}"
  loop_control:
    label: "{{ _logrotate_item.filename }}"
  vars:
    # if item is a dict, use this dict, else search in _logrotate_entries dict
    _logrotate_item: "{{ item if item is mapping else _logrotate_entries[item] }}"
