- block:
  - name: check pgdg version
    fail:
      msg: "pgdg version must be one of {{ _pgdg_available_versions | join(', ')  }}"
    when: _pgdg_version not in _pgdg_available_versions

  - name: "pgdg 路 {{ _pgdg_version }} 路 rpm key"
    copy:
      dest: "{{ _pgdg_key_dest }}"
      src: "{{ _pgdg_key_src }}"
      owner: root
      group: root
      mode: u=rw,g=r,o=r

  - name: "pgdg 路 {{ _pgdg_version }} 路 .repo"
    yum_repository:
      name: pgdg{{ _pgdg_version_stripped }}
      description: PostgreSQL {{ _pgdg_version }} $releasever - $basearch
      baseurl: https://download.postgresql.org/pub/repos/yum/{{ _pgdg_version }}/redhat/rhel-$releasever-$basearch
      enabled: yes
      file: pgdg-{{ _pgdg_version_stripped }}-centos
      gpgcheck: yes
      gpgkey: file://{{ _pgdg_key_dest }}

  vars:
    _pgdg_version: "{{ pgdg_version }}"
    _pgdg_version_stripped: "{{ pgdg_version.replace('.', '') }}"
    _pgdg_key_src: RPM-GPG-KEY-PGDG
    _pgdg_key_dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG-{{ _pgdg_version_stripped }}
