- name: "postgresql · {{ _postgresql_version }} · rpm install"
  package:
    name: "{{ package }}"
    state: installed
  with_items: "{{ postgresql_packages + postgresql_default_packages }}"
  loop_control:
    loop_var: package

  vars:
    _postgresql_version: "{{ postgresql_version }}"
    _postgresql_version_stripped: "{{ postgresql_version.replace('.', '') }}"
