- block:
  - set_fact: {"{{ java_results_var }}": {}}
    when: java_results_var not in hostvars[inventory_hostname]

  - name: install
    include_tasks: java_runtime_item.yml
    with_items: "{{ java_runtimes }}"
    loop_control:
      label: "{{ item.key }}"

  when: java_runtimes | length > 0
