- name: vagrant folder
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ _vagrant_root_path }}"
    - "{{ _vagrant_path }}"

- name: vagrantfile
  template:
    src: Vagrantfile.j2
    dest: "{{ _vagrant_path }}/Vagrantfile"
  register: vagrantfile

- name: vagrant status
  shell: vagrant status --machine-readable | grep state,running
  args:
    chdir: "{{ _vagrant_path }}"
  environment:
    VAGRANT_DEFAULT_PROVIDER: "{{ _vagrant_provider }}"
  register: vagrant_status
  ignore_errors: yes
  changed_when: no

- name: vagrant up
  shell: vagrant up
  args:
    chdir: "{{ _vagrant_path }}"
  environment:
    VAGRANT_DEFAULT_PROVIDER: "{{ _vagrant_provider }}"
  when: vagrant_status.rc != 0

- name: vagrant ssh_config extract
  shell: vagrant ssh-config --host "{{ _vagrant_host }}"
  args:
    chdir: "{{ _vagrant_path }}"
  environment:
    VAGRANT_DEFAULT_PROVIDER: "{{ _vagrant_provider }}"
  register: ssh_config
  changed_when: no

- name: vagrant ssh_config save
  copy:
    dest: "{{ _vagrant_path }}/ssh_config"
    content: "{{ ssh_config.stdout }}"
