---

- name: elasticsearch.reload
  become: yes
  become_user: root
  service:
    name: "{{ _elasticsearch_unit_name }}"
    state: reloaded

- name: elasticsearch.restart
  become: yes
  become_user: root
  service:
    name: "{{ _elasticsearch_unit_name }}"
    state: restarted

- name: elasticsearch.start
  become: yes
  become_user: root
  service:
    name: "{{ _elasticsearch_unit_name }}"
    state: started

- name: elasticsearch.stop
  become: yes
  become_user: root
  service:
    name: "{{ _elasticsearch_unit_name }}"
    state: stopped

- name: elasticsearch.systemd.daemon_reload
  become: yes
  become_user: root
  systemd:
    name: "{{ _elasticsearch_unit_name }}"
    daemon_reload: yes
