---
- name: lxml · allow xml parsing
  package:
    name: python-lxml
  become: yes
  become_user: root

- name: prepare download folder
  file:
    path: "{{ _elasticsearch_download_target | dirname }}"
    state: directory
  become: yes
  become_user: root

- name: download
  get_url:
    url: "{{ _elasticsearch_download_url }}"
    dest: "{{ _elasticsearch_download_target }}"
  become: yes
  become_user: root

- name: prepare home folder
  file:
    path: "{{ _elasticsearch_install_dest }}"
    state: directory
  become: yes
  become_user: root

- name: extract
  unarchive:
    src: "{{ _elasticsearch_download_target }}"
    remote_src: yes
    dest: "{{ _elasticsearch_install_dest }}"
    exclude:
      - "config/elasticsearch.yml"
    extra_opts:
      - --strip-components=1
  become: yes
  become_user: root

- name: base folder
  file:
    path: "{{ path }}"
    state: directory
    mode: u=rwX
    owner: "{{ _elasticsearch_user }}"
    group: "{{ _elasticsearch_group }}"
  with_items:
    - "{{ _elasticsearch_base_path }}"
    - "{{ _elasticsearch_conf_path }}"
    - "{{ _elasticsearch_data_path }}"
    - "{{ _elasticsearch_scripts_path }}"
    - "{{ _elasticsearch_plugins_path }}"
    - "{{ _elasticsearch_logs_path }}"
  loop_control:
    loop_var: path
  become: yes
  become_user: root

- name: config file
  template:
    src: elasticsearch.conf.j2
    dest: "{{ _elasticsearch_conf_path }}/elasticsearch.yml"
    owner: "{{ _elasticsearch_user }}"
    group: "{{ _elasticsearch_group }}"
    mode: u=rw
  become: yes
  become_user: root

##
## logging.yml
##

- name: instance logging.yml file (check)
  stat:
    path: "{{ _elasticsearch_conf_path }}/logging.yml"
  register: logging_stat
  become: yes
  become_user: root

- name: dist logging.yml file (check)
  stat:
    path: "{{ _elasticsearch_install_dest }}/config/logging.yml"
  register: logging_dist_stat
  become: yes
  become_user: root

- name:
  copy:
    src: "{{ _elasticsearch_install_dest }}/config/logging.yml"
    remote_src: yes
    dest: "{{ _elasticsearch_conf_path }}/logging.yml"
    owner: "{{ _elasticsearch_user }}"
    group: "{{ _elasticsearch_group }}"
    mode: u=rw
  # elasticsearch 5.x is logging.yml-less; skip in this case
  # needed for ES 2.x
  when: logging_dist_stat.stat.exists and not logging_stat.stat.exists
  become: yes
  become_user: root

##
## log4j2.properties
##

- name: instance log4j2.properties file (check)
  stat:
    path: "{{ _elasticsearch_conf_path }}/log4j2.properties"
  register: log4j2_stat
  become: yes
  become_user: root

- name: dist log4j2.properties file (check)
  stat:
    path: "{{ _elasticsearch_install_dest }}/config/log4j2.properties"
  register: log4j2_dist_stat
  become: yes
  become_user: root

- name:
  copy:
    src: "{{ _elasticsearch_install_dest }}/config/log4j2.properties"
    remote_src: yes
    dest: "{{ _elasticsearch_conf_path }}/log4j2.properties"
    owner: "{{ _elasticsearch_user }}"
    group: "{{ _elasticsearch_group }}"
    mode: u=rw
  # elasticsearch 2.x is log4j2.properties-less; skip in this case
  # needed for ES 5.x
  when: log4j2_dist_stat.stat.exists and not log4j2_stat.stat.exists
  become: yes
  become_user: root

##
## jvm.options
##

- name: instance jvm.options file (check)
  stat:
    path: "{{ _elasticsearch_conf_path }}/jvm.options"
  register: jvmoptions_stat
  become: yes
  become_user: root

- name: dist jvm.options file (check)
  stat:
    path: "{{ _elasticsearch_install_dest }}/config/jvm.options"
  register: jvmoptions_dist_stat
  become: yes
  become_user: root

- name:
  copy:
    src: "{{ _elasticsearch_install_dest }}/config/jvm.options"
    remote_src: yes
    dest: "{{ _elasticsearch_conf_path }}/jvm.options"
    owner: "{{ _elasticsearch_user }}"
    group: "{{ _elasticsearch_group }}"
    mode: u=rw
  # elasticsearch 2.x is jvm.options-less; skip in this case
  # needed for ES 5.x
  when: jvmoptions_dist_stat.stat.exists and not jvmoptions_stat.stat.exists
  become: yes
  become_user: root

- name: memory (>=5.x)
  # only for ES 5.x
  when: _elasticsearch_version is version('5.0.0', '>=')
  become: yes
  become_user: root
  block:
    - name:
      lineinfile:
        path: "{{ _elasticsearch_conf_path }}/jvm.options"
        regexp: "^-Xms.*$"
        line: "-Xms{{ _elasticsearch_mem_min }}"

    - name:
      lineinfile:
        path: "{{ _elasticsearch_conf_path }}/jvm.options"
        regexp: "^-Xmx.*$"
        line: "-Xmx{{ _elasticsearch_mem_max }}"

    - name:
      blockinfile:
        path: "{{ _elasticsearch_conf_path }}/jvm.options"
        marker: "## {mark} ANSIBLE MANAGED elasticsearch_java_opts"
        block: |-
          {% for item in _elasticsearch_java_opts %}
          {{ item }}
          {% endfor %}

- name: plugins not supported for ES 5.x
  fail:
    msg: plugins are not supported by this role for ES >= 5.x
  when: >-
    _elasticsearch_plugins | length > 0
    and _elasticsearch_version is version('5.0.0', '>=')

- name: plugins
  include: plugin.yml
  with_items: "{{ _elasticsearch_plugins }}"
  loop_control:
    loop_var: plugin
    label: "{{ plugin.name }}"

- name: ensure systemd service configuration
  become: yes
  become_user: root
  template:
    src: elasticsearch.service.j2
    dest: /etc/systemd/system/{{ _elasticsearch_unit_name }}.service
    mode: u=rw,g=rw,o=r
  notify: elasticsearch.systemd.daemon_reload

- name: enable service
  become: yes
  become_user: root
  service:
    name: "{{ elasticsearch_unit_name }}"
    enabled: yes
    state: started
