
- hosts: "{{ custom_hosts | default('all') }}"
  roles:
    - role: igloo.main.kobackup
      when: playbook_kobackup_enabled
      dumps_infos:
        - target_basename: "{{ playbook_kobackup_dump_target_basename | default(playbook_postgresql_database) }}"
          target_path: "{{ playbook_kobackup_dump_target_path }}"
          database: "{{ playbook_kobackup_dump_database }}"
          hostname: "{{ playbook_kobackup_dump_hostname }}"
          port: "{{ playbook_kobackup_dump_port }}"
          user: "{{ playbook_kobackup_dump_username }}"
          password: "{{ playbook_kobackup_dump_password }}"
          sudo: "{{ playbook_kobackup_dump_sudo }}"
      backup_paths: "{{ playbook_kobackup_backup_paths }}"
      restic_repository: "{{ playbook_kobackup_restic_repository }}"
      restic_password: "{{ playbook_kobackup_restic_password }}"
      restic_forget_prune: "{{ playbook_kobackup_restic_forget_prune }}"
      aws_access_key_id: "{{ playbook_kobackup_restic_aws_access_key_id }}"
      aws_secret_access_key: "{{ playbook_kobackup_restic_aws_secret_access_key }}"
      s3_conf_path: "{{ playbook_kobackup_s3_conf_path }}"
      kobackup_conf_path: "{{ playbook_kobackup_conf_path }}"
      kobackup_service_name: "{{ playbook_kobackup_service_name }}"
      kobackup_timer_unit_description: "{{ playbook_kobackup_timer_description }}"
      kobackup_timer_oncalendar: "{{ playbook_kobackup_timer_oncalendar }}"
      kobackup_clone: "{{ playbook_kobackup_clone | default({}) }}"
      restic_version: "{{ playbook_kobackup_restic_version }}"
      tags: kobackup