- name: war · copy war
  copy:
    src: "{{ war_application_war_src }}"
    dest: "{{ war_application_war_target }}"
    remote_src: "{{ war_application_war_remote_src }}"
    owner: "{{ war_application_user }}"
    group: "{{ war_application_user }}"
    mode: u=rw,g=r,o=r
  register: war

- block:
  - name: war · stop application
    service:
      name: "{{ war_tomcat_service }}"
      state: stopped
  - name: war · wait application stop
    wait_for:
      path: "{{ war_tomcat_catalina_pid }}"
      state: absent
  - name: war · clean
    shell: >-
        rm -rf "{{ war_tomcat_catalina_base }}/work/"*
        "{{ war_tomcat_catalina_base }}/temp/"*
        "{{ war_tomcat_catalina_base }}/webapps/{{ war_application_war_target | basename }}"
        "{{ war_tomcat_catalina_base }}/webapps/{{ war_application_war_target | basename | splitext | first }}"
    args:
      warn: off
  - name: war . copy war
    copy:
      src: "{{ war_application_war_target }}"
      dest: "{{ war_tomcat_catalina_base }}/webapps/{{ war_application_war_target | basename }}"
      remote_src: yes
      owner: "{{ war_application_user }}"
      group: "{{ war_application_user }}"
      mode: u=rw,g=r,o=r
  - name: war · start application
    service:
      name: "{{ war_tomcat_service }}"
      state: started
  when: war.changed
