- name: war . copy war
  copy:
    src: "{{ _war_application_war_src }}"
    remote_src: "{{ _war_application_war_remote_src }}"
    dest: "{{ _war_tomcat_catalina_base }}/webapps/{{ _war_context_name_or_root }}.war"
    owner: "{{ _war_application_user }}"
    group: "{{ _war_application_user }}"
    mode: u=rw,g=r,o=r
  register: war
  check_mode: yes

- block:
  - name: war · stop application
    service:
      name: "{{ _war_tomcat_service }}"
      state: stopped

  - name: war · wait application stop
    wait_for:
      path: "{{ _war_tomcat_catalina_pid }}"
      state: absent

  - name: war · clean
    shell: >-
        rm -rf "{{ _war_tomcat_catalina_base }}/work/"*
        "{{ _war_tomcat_catalina_base }}/temp/"*
        "{{ _war_tomcat_catalina_base }}/webapps/{{ _war_context_name_or_root }}.war"
        "{{ _war_tomcat_catalina_base }}/webapps/{{ _war_context_name_or_root }}"
    args:
      warn: off

  - name: war · copy war
    copy:
      src: "{{ _war_application_war_src }}"
      remote_src: "{{ _war_application_war_remote_src }}"
      dest: "{{ _war_tomcat_catalina_base }}/webapps/{{ _war_context_name_or_root }}.war"
      owner: "{{ _war_application_user }}"
      group: "{{ _war_application_user }}"
      mode: u=rw,g=r,o=r

  - name: war · start application
    service:
      name: "{{ _war_tomcat_service }}"
      state: started
  when: war.changed
